#!/bin/bash

export LOCAL_UID=$(id -u)
export LOCAL_GID=$(id -g)
export LOCAL_USERNAME=$(whoami)



if [ "$1" == 'up' ]; then
    docker-compose up --build -d
elif [ "$1" == 'down' ]; then
    docker-compose down
elif [ "$1" == 'logs' ]; then
    docker-compose logs -f
elif [ "$1" == 'restart' ]; then
    docker-compose down
    docker-compose up -d --build
elif [ "$1" == 'sh' ]; then
    docker exec -it java-app /bin/bash
elif [ "$1" == 'postgres' ]
    docker exec -it lab-bd-postgres-1 psql -h postgres -p 5432 -U user -d iot_data
elif [ "$1" == 'redis' ]; then
    docker exec -it redis redis-cli

else
    echo "Invalid argument"
fi
