
services:
  app:
    build: .
    container_name: java-app
    volumes:
      - .:/workspace  # Mount the current directory into the container
    ports:
      - "8080:8080"  # Expose your Java application port
    depends_on:
      - redis
    networks:
      - dev-network
  redis:
    image: "redis:latest"
    container_name: redis-db
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
