-- Insert new rows into PAIS
INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) VALUES (22, 'Coreia do Sul', 'Ásia', 51780579);
INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) VALUES (23, 'Suécia', 'Europa', 10327589);
INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) VALUES (24, 'Noruega', 'Europa', 5421241);
INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) VALUES (25, 'Dinamarca', 'Europa', 5831404);
INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) VALUES (26, 'Finlândia', 'Europa', 5540720);

-- Insert new rows into OLIMPIADA
INSERT INTO OLIMPIADA (ANO, PAIS, CIDADE_SEDE, DATA_INICIO, DATA_ENCERRAMENTO) 
VALUES (2024, 'França', 'Paris', TO_DATE('2024-07-26', 'YYYY-MM-DD'), TO_DATE('2024-08-11', 'YYYY-MM-DD'));
INSERT INTO OLIMPIADA (ANO, PAIS, CIDADE_SEDE, DATA_INICIO, DATA_ENCERRAMENTO) 
VALUES (2028, 'Estados Unidos', 'Los Angeles', TO_DATE('2028-07-21', 'YYYY-MM-DD'), TO_DATE('2028-08-06', 'YYYY-MM-DD'));
INSERT INTO OLIMPIADA (ANO, PAIS, CIDADE_SEDE, DATA_INICIO, DATA_ENCERRAMENTO) 
VALUES (2032, 'Austrália', 'Brisbane', TO_DATE('2032-07-23', 'YYYY-MM-DD'), TO_DATE('2032-08-08', 'YYYY-MM-DD'));
INSERT INTO OLIMPIADA (ANO, PAIS, CIDADE_SEDE, DATA_INICIO, DATA_ENCERRAMENTO) 
VALUES (2036, 'Alemanha', 'Berlin', TO_DATE('2036-07-24', 'YYYY-MM-DD'), TO_DATE('2036-08-09', 'YYYY-MM-DD'));
INSERT INTO OLIMPIADA (ANO, PAIS, CIDADE_SEDE, DATA_INICIO, DATA_ENCERRAMENTO) 
VALUES (2040, 'China', 'Shanghai', TO_DATE('2040-07-25', 'YYYY-MM-DD'), TO_DATE('2040-08-10', 'YYYY-MM-DD'));

-- Insert new rows into LOCAL
INSERT INTO LOCAL (ID, NOME, TIPO, CAPACIDADE, PAIS) VALUES (11, 'Stade de France', 'ESTAGIO', 81338, 'França');
INSERT INTO LOCAL (ID, NOME, TIPO, CAPACIDADE, PAIS) VALUES (12, 'Los Angeles Memorial Coliseum', 'ESTAGIO', 77500, 'Estados Unidos');
INSERT INTO LOCAL (ID, NOME, TIPO, CAPACIDADE, PAIS) VALUES (13, 'Brisbane Cricket Ground', 'ESTAGIO', 42000, 'Austrália');
INSERT INTO LOCAL (ID, NOME, TIPO, CAPACIDADE, PAIS) VALUES (14, 'Olympiastadion Berlin', 'ESTAGIO', 74475, 'Alemanha');
INSERT INTO LOCAL (ID, NOME, TIPO, CAPACIDADE, PAIS) VALUES (15, 'Shanghai Stadium', 'ESTAGIO', 80000, 'China');

-- Insert new rows into MODALIDADE
INSERT INTO MODALIDADE (ID, ESPORTE, GENERO) VALUES (12, 'Basquete', 'M');
INSERT INTO MODALIDADE (ID, ESPORTE, GENERO) VALUES (13, 'Basquete', 'F');
INSERT INTO MODALIDADE (ID, ESPORTE, GENERO) VALUES (14, 'Handebol', 'M');
INSERT INTO MODALIDADE (ID, ESPORTE, GENERO) VALUES (15, 'Handebol', 'F');
INSERT INTO MODALIDADE (ID, ESPORTE, GENERO) VALUES (16, 'Tênis', 'M');

-- Insert new rows into PATROCINADOR
INSERT INTO PATROCINADOR (ID, NOME, RAMO) VALUES (1, 'Nike', 'Esportes');
INSERT INTO PATROCINADOR (ID, NOME, RAMO) VALUES (2, 'Adidas', 'Esportes');
INSERT INTO PATROCINADOR (ID, NOME, RAMO) VALUES (3, 'Puma', 'Esportes');
INSERT INTO PATROCINADOR (ID, NOME, RAMO) VALUES (4, 'Samsung', 'Tecnlogia');
INSERT INTO PATROCINADOR (ID, NOME, RAMO) VALUES (5, 'Toyota', 'Automobilistica');

-- Insert new rows into ATLETA
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('1', 'U. Bolt', 'Jamaica', 'M', 1);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('2', 'M. Phelps', 'Estados Unidos', 'M', 3);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('3', 'S. Biles', 'Estados Unidos', 'F', 6);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('4', 'Neymar', 'Brasil', 'M', 11);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('5', 'N.Djokovic', 'Sérvia', 'M', 16);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('6', 'L. Messi', 'Argentina', 'M', 17);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('7', 'C. Ronaldo', 'Portugal', 'M', 17);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('8', 'R. Federer', 'Suíça', 'M', 16);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('9', 'R. Nadal', 'Espanha', 'M', 16);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('10', 'L.Hamilton', 'Reino Unido', 'M', 18);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('11', 'S.Williams', 'Estados Unidos', 'F', 19);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('12', 'K. Bryant', 'Estados Unidos', 'M', 12);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('13', 'M. Vieira da Silva', 'Brasil', 'F', 20);
INSERT INTO ATLETA (PASSAPORTE, NOME, PAIS, GENERO, MODALIDADE) VALUES ('14', 'T. Brady', 'Estados Unidos', 'M', 21);

-- Insert new rows into MIDIA
INSERT INTO MIDIA (ID, NOME, TIPO) VALUES (1, 'NBC', 'TV');
INSERT INTO MIDIA (ID, NOME, TIPO) VALUES (2, 'BBC', 'TV');
INSERT INTO MIDIA (ID, NOME, TIPO) VALUES (3, 'ESPN', 'TV');
INSERT INTO MIDIA (ID, NOME, TIPO) VALUES (4, 'Fox Sports', 'TV');
INSERT INTO MIDIA (ID, NOME, TIPO) VALUES (5, 'CCTV', 'TV');

-- Insert rows into JOGA table
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('M. Phelps', 61);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 63);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('Neymar', 67);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('Neymar', 68);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('U. Bolt', 73);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 75);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 76);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('Neymar', 77);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('M. Phelps', 78);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 79);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('M. Phelps', 80);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('U. Bolt', 81);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('M. Phelps', 82);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 83);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('Neymar', 84);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('N.Djokovic', 85);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('U. Bolt', 86);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 87);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('Neymar', 88);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('M. Phelps', 89);
INSERT INTO JOGA (ATLETA, DISPUTA) VALUES ('S. Biles', 90);


-- Insert rows into DISPUTA table
-- Insert rows into DISPUTA table
INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (200, 'Brasil', 'Estados Unidos', 'Brasil', 3, 2024, TO_DATE('2024-08-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (201, 'China', 'Japão', 'China', 3, 2024, TO_DATE('2024-08-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (202, 'Alemanha', 'França', 'Alemanha', 3, 2024, TO_DATE('2024-08-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (203, 'Reino Unido', 'Rússia', 'Reino Unido', 3, 2024, TO_DATE('2024-08-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (204, 'Brasil', 'China', 'Brasil', 3, 2024, TO_DATE('2024-08-12 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (205, 'Alemanha', 'Reino Unido', 'Alemanha', 3, 2024, TO_DATE('2024-08-12 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (206, 'Brasil', 'Alemanha', 'Brasil', 3, 2024, TO_DATE('2024-08-14 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (207, 'Brasil', 'Alemanha', 'Brasil', 6, 2024, TO_DATE('2024-08-16 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (208, 'Estados Unidos', 'China', 'Estados Unidos', 6, 2024, TO_DATE('2024-08-16 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (209, 'Japão', 'França', 'Japão', 6, 2024, TO_DATE('2024-08-16 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (210, 'Rússia', 'Reino Unido', 'Rússia', 6, 2024, TO_DATE('2024-08-16 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (211, 'Austrália', 'Nigéria', 'Austrália', 6, 2024, TO_DATE('2024-08-16 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (212, 'Brasil', 'Estados Unidos', 'Brasil', 6, 2024, TO_DATE('2024-08-18 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (213, 'Japão', 'Rússia', 'Japão', 6, 2024, TO_DATE('2024-08-18 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (214, 'Austrália', 'Brasil', 'Brasil', 6, 2024, TO_DATE('2024-08-20 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (215, 'Japão', 'Brasil', 'Brasil', 6, 2024, TO_DATE('2024-08-22 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (216, 'Brasil', 'Alemanha', 'Brasil', 11, 2024, TO_DATE('2024-08-24 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (217, 'Estados Unidos', 'China', 'Estados Unidos', 11, 2024, TO_DATE('2024-08-24 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (218, 'Japão', 'França', 'Japão', 11, 2024, TO_DATE('2024-08-24 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (381, 'Brasil', 'Argentina', 'Brasil', 11, 2024, TO_DATE('2024-08-26 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (382, 'Canadá', 'México', 'Canadá', 11, 2024, TO_DATE('2024-08-26 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (383, 'Itália', 'Espanha', 'Itália', 11, 2024, TO_DATE('2024-08-26 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (384, 'Portugal', 'Holanda', 'Portugal', 11, 2024, TO_DATE('2024-08-26 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (385, 'Suécia', 'Noruega', 'Suécia', 11, 2024, TO_DATE('2024-08-26 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (386, 'Dinamarca', 'Finlândia', 'Dinamarca', 11, 2024, TO_DATE('2024-08-28 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (387, 'Suíça', 'Áustria', 'Suíça', 11, 2024, TO_DATE('2024-08-28 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (388, 'Bélgica', 'Holanda', 'Bélgica', 11, 2024, TO_DATE('2024-08-28 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (389, 'Grécia', 'Turquia', 'Grécia', 11, 2024, TO_DATE('2024-08-28 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (390, 'Egito', 'Marrocos', 'Egito', 11, 2024, TO_DATE('2024-08-28 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);
INSERT INTO DISPUTA (ID, PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL) 
VALUES (393, 'Rússia', 'Reino Unido', 'Rússia', 11, 2024, TO_DATE('2024-08-24 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10);

-- Insert rows into L11_TRANSMITE table
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (1, 61);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (2, 62);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (3, 63);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (4, 64);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (5, 65);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (6, 66);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (7, 67);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (8, 68);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (9, 69);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (10, 70);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (11, 71);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (12, 72);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (13, 73);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (14, 74);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (15, 75);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (16, 76);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (17, 77);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (18, 78);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (19, 79);
INSERT INTO L11_TRANSMITE (MIDIA, DISPUTA) VALUES (20, 80);

-- Insert rows into PATROCINA table
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (16, 'L. Messi', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1600000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (17, 'C. Ronaldo', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1700000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (18, 'R. Federer', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1800000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (19, 'R. Nadal', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1900000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (20, 'L.Hamilton', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 2000000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (1, 'M. Phelps', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 500000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (2, 'S. Biles', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 400000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (3, 'Neymar', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 300000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (4, 'U. Bolt', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 200000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (5, 'N.Djokovic', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 100000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (6, 'L. Messi', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 600000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (7, 'S.Williams', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 700000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (8, 'C. Ronaldo', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 800000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (9, 'R. Federer', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 900000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (10, 'R. Nadal', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1000000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (11, 'L.Hamilton', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1100000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (12, 'K. Bryant', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1200000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (13, 'M. Vieira da Silva', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1300000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (14, 'S.Williams', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1400000);
INSERT INTO PATROCINA (PATROCINADOR, ATLETA, INICIO, VIGENCIA, VALOR_TOTAL) 
VALUES (15, 'T. Brady', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 12, 1500000);
