



-- exercicio 1
SELECT PAIS1, PAIS2, VENCEDOR, MODALIDADE, OLIMPIADA, DATA_HORA, LOCAL FROM L05_DISPUTA
WHERE DATA_HORA = TO_DATE('2016-08-06 10:00:00', 'YYYY-MM-DD HH24:MI:SS');
 
-- exercicio 2 nao entendi o que é um evento
SELECT nome from local;

-- SELECT * FROM DISPUTA GROUP BY LOCAL;

-- exercicio 3

SELECT 
    A.NOME AS atleta_nome,
    O.ANO AS ano,
    SUM(P.VALOR_TOTAL / P.VIGENCIA) AS ganho_anual
FROM 
    JOGA J
JOIN 
    ATLETA A ON J.ATLETA = A.PASSAPORTE
JOIN 
    DISPUTA D ON J.DISPUTA = D.ID
JOIN 
    OLIMPIADA O ON D.OLIMPIADA = O.ANO
JOIN 
    PATROCINA P ON P.ATLETA = A.PASSAPORTE
WHERE 
    O.ANO BETWEEN P.INICIO AND (P.INICIO + P.VIGENCIA - 1)
GROUP BY 
    A.NOME, O.ANO
ORDER BY 
    A.NOME, O.ANO;
